version: "3.1"
services:
    app:
        build: .
        networks:
            billing_network:
                ipv4_address: 172.25.0.2
        ports:
            - "8001:80"
        volumes:
            - ./src:/var/www/html/
        links:
            - db
        extra_hosts:
            - "example-domain.local:172.25.0.2"
    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: name_database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        networks:
            billing_network:
                    ipv4_address: 172.25.0.4
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
networks:
    billing_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.25.0.1/24

